### PR TITLE
WIP: Ops 4426

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Comment by attiks** [comment]
Still needs the libraries into the composer file

**Comment by attiks** [comment]
@cafuego FYI

According to the docs it should work with `oomphinc/composer-installers-extender`, as described on https://asset-packagist.org/site/about, but alas

Only way I can think of is using post-cmds.

If you know a cleaner solution, let me know

**Comment by cafuego** [comment]
Huh, libraries are conveniently ignored by the docs in drupal.org? Typical. 

Oh, I see ... they're managed outside of composer and won't get deleted because `html/sites/all/libraries` is listed as a path that should be ignored by composer. 

I did a bit of searching and I came across http://cgit.drupalcode.org/chosen/tree/README.txt?h=8.x-2.x as an example. That could work if we specify `html/sites/all/libraries` as install path for the `drupal-library` type and remove it from the `preserve-paths` list.

**Comment by attiks** [comment]
At least in the case of events this is not going to work, tried it in various ways, but will be very cumbersome to maintain, it's a mix of js and php libraries some extended with an extra plugin file, some patched for this project, so I'm going to remove all the cruft from composer.json

**Pull request merged**
