### PR TITLE
OPS-4044: Config files to run upgrade tests

### PR DESCRIPTION
**Pull request by attiks**
Steps needed on Jenkins

- Prep site as usual
- git clone git@github.com:UN-OCHA/drupal-update-checker.git
- cd drupal-update-checker
- ./run_upgrade.sh

### CODE REVIEW

**Comment by attiks** [comment]
The duc commands probably needs to be adopted to use env parameters

**Comment by emmajane** [comment]
@cafuego To confirm, is the "we" the royal we meaning Cafuego, or was this more something you wanted specific feedback on from @attiks? Asking because we weren't sure in the dev standup today whose problem it was to tackle next. :)

**Comment by cafuego** [comment]
It’s definitely the royal “we” in this case. l’ve added some more detail about what I’m doing on the actual ticket.

**Comment by attiks** [comment]
backstop/urls_anon.txt.template and backstop/urls_auth.txt.template are not used during testing

**Comment by attiks** [comment]
Should be picked up by https://github.com/UN-OCHA/drupal-update-checker/blob/ops/4044-automagic/anonymous.js#L10

**Pull request merged**
