### PR TITLE
ES-67: Behat testing

### PR DESCRIPTION
**Pull request by attiks**
- use google chrome headless
- build theme css
- use sqlite for speed
- codesniff
- behat

### CODE REVIEW

**Comment by attiks** [comment]
Do not merge this (yet)

**Comment by attiks** [comment]
@cafuego why are tests run twice?

**Comment by cafuego** [comment]
Travis runs 'em for the PR and for the push; that can be changed.

**Comment by attiks** [comment]
Can we do PR only, not on commits not part of a PR?

**Pull request merged**
